-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language pseudoXMLgrammatica.

module AbsPseudoXMLgrammatica where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data SourceFile = SourceFile File
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data File
    = SimpleFile [SectionDecl] | FileWImport [Import] [SectionDecl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Import = FileImport FilePath
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FilePath = Path String
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SectionDecl = SectionDecl Ident SectionContent
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SectionContent
    = SimpleSecCont [FieldDecl] | SecContent [Inherit] [FieldDecl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Inherit = InheritSection SectionName
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SectionName = SecName Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FieldDecl = FieldDeclar Ident Value
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Value
    = ValueInt Integer
    | ValueBool Boolean
    | ValueString String
    | ValueNonLoc NonLocVar
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Boolean = Boolean_true | Boolean_false
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data NonLocVar = SimpleNonLoc Ident | NonLoc Ident Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

