## File generated by the BNF Converter (bnfc 2.9.6.1).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestPseudoXMLgrammatica

# Rules for building the parser.

AbsPseudoXMLgrammatica.hs LexPseudoXMLgrammatica.x ParPseudoXMLgrammatica.y PrintPseudoXMLgrammatica.hs TestPseudoXMLgrammatica.hs : pseudoXMLgrammatica.cf
	bnfc --haskell pseudoXMLgrammatica.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

TestPseudoXMLgrammatica : AbsPseudoXMLgrammatica.hs LexPseudoXMLgrammatica.hs ParPseudoXMLgrammatica.hs PrintPseudoXMLgrammatica.hs TestPseudoXMLgrammatica.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsPseudoXMLgrammatica.hs AbsPseudoXMLgrammatica.hs.bak ComposOp.hs ComposOp.hs.bak DocPseudoXMLgrammatica.txt DocPseudoXMLgrammatica.txt.bak ErrM.hs ErrM.hs.bak LayoutPseudoXMLgrammatica.hs LayoutPseudoXMLgrammatica.hs.bak LexPseudoXMLgrammatica.x LexPseudoXMLgrammatica.x.bak ParPseudoXMLgrammatica.y ParPseudoXMLgrammatica.y.bak PrintPseudoXMLgrammatica.hs PrintPseudoXMLgrammatica.hs.bak SkelPseudoXMLgrammatica.hs SkelPseudoXMLgrammatica.hs.bak TestPseudoXMLgrammatica.hs TestPseudoXMLgrammatica.hs.bak XMLPseudoXMLgrammatica.hs XMLPseudoXMLgrammatica.hs.bak ASTPseudoXMLgrammatica.agda ASTPseudoXMLgrammatica.agda.bak ParserPseudoXMLgrammatica.agda ParserPseudoXMLgrammatica.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak pseudoXMLgrammatica.dtd pseudoXMLgrammatica.dtd.bak TestPseudoXMLgrammatica LexPseudoXMLgrammatica.hs ParPseudoXMLgrammatica.hs ParPseudoXMLgrammatica.info ParDataPseudoXMLgrammatica.hs Makefile


# EOF
