## File generated by the BNF Converter (bnfc 2.9.6.1).

CC = gcc -g
CCFLAGS = -std=c11 -W -Wall -Wsign-conversion -Wno-unused-parameter -Wno-unused-function -Wno-unneeded-internal-declaration ${CC_OPTS}

FLEX = flex
FLEX_OPTS = -Ppseudo_xm_lgrammatica_

BISON = bison
BISON_OPTS = -t -ppseudo_xm_lgrammatica_


# Aggiunti comment_tracker.o e printer.o alla lista degli oggetti
OBJS = Absyn.o Buffer.o Lexer.o Parser.o ParserSupport.o ReferenceSolver.o comment_tracker.o Printer.o

.PHONY : clean distclean

all : TestProgram

clean :
	rm -f *.o TestProgram pseudoXMLgrammatica.aux pseudoXMLgrammatica.log pseudoXMLgrammatica.pdf pseudoXMLgrammatica.dvi pseudoXMLgrammatica.ps pseudoXMLgrammatica

distclean : clean
	rm -f Absyn.h Absyn.c Bison.h Buffer.h Buffer.c pseudoXMLgrammatica.l Lexer.c pseudoXMLgrammatica.y Parser.h Parser.c Test.c Makefile pseudoXMLgrammatica.tex

TestProgram : ${OBJS} TestProgram.o
	@echo "Linking TestProgram..."
	${CC} ${OBJS} TestProgram.o -o TestProgram

Absyn.o : Absyn.c Absyn.h
	${CC} ${CCFLAGS} -c Absyn.c

Buffer.o : Buffer.c Buffer.h
	${CC} ${CCFLAGS} -c Buffer.c

# Regola per il comment tracker
comment_tracker.o : comment_tracker.c comment_tracker.h
	${CC} ${CCFLAGS} -c comment_tracker.c

# Regola per il printer (dipende da Absyn per la struttura dell'AST)
Printer.o : Printer.c Printer.h Absyn.h ParserSupport.h
	${CC} ${CCFLAGS} -c printer.c

Lexer.c : Lexer.l
	${FLEX} ${FLEX_OPTS} -oLexer.c Lexer.l

Parser.c Bison.h : Parser.y
	${BISON} ${BISON_OPTS} --defines=Bison.h Parser.y -o Parser.c

Lexer.o : CCFLAGS+=-Wno-sign-conversion

# Lexer ora dipende anche da comment_tracker.h
Lexer.o : Lexer.c Bison.h comment_tracker.h
	${CC} ${CCFLAGS} -c Lexer.c

Parser.o : Parser.c Absyn.h Bison.h ParserSupport.h
	${CC} ${CCFLAGS} -c Parser.c

ReferenceSolver.o : ReferenceSolver.c ParserSupport.h
	${CC} ${CCFLAGS} -c ReferenceSolver.c

ParserSupport.o : ParserSupport.c ParserSupport.h Absyn.h
	${CC} ${CCFLAGS} -c ParserSupport.c

# Aggiornate dipendenze del TestProgram
TestProgram.o : TestProgram.c Parser.h Absyn.h printer.h comment_tracker.h
	${CC} ${CCFLAGS} -c TestProgram.c

# Aggiunti i nuovi file al target zip
zip: Absyn.c Absyn.h Bison.h Buffer.c Buffer.h Deletion.c Lexer.l Makefile Parser.h ParserSupport.c ParserSupport.h Parser.y PseudoXML.cf ReferenceSolver.c Test.c comment_tracker.c comment_tracker.h Printer.c Printer.h tests
	zip ProgettoLC\ parte1\ Gruppo\ 25-3.zip Absyn.c Absyn.h Bison.h Buffer.c Buffer.h Deletion.c Lexer.l Makefile Parser.h ParserSupport.c ParserSupport.h Parser.y PseudoXML.cf ReferenceSolver.c Test.c comment_tracker.c comment_tracker.h Printer.c Printer.h tests
