## File generated by the BNF Converter (bnfc 2.9.6.1).

CC = gcc -g
CCFLAGS = -std=c11 -W -Wall -Wsign-conversion -Wno-unused-parameter -Wno-unused-function -Wno-unneeded-internal-declaration ${CC_OPTS}

FLEX = flex
FLEX_OPTS = -Ppseudo_xm_lgrammatica_

BISON = bison
BISON_OPTS = -t -ppseudo_xm_lgrammatica_

OBJS = Absyn.o Buffer.o Lexer.o Parser.o ParserSupport.o ReferenceSolver.o

.PHONY : clean distclean

all : TestProgram

clean :
	rm -f *.o TestpseudoXMLgrammatica pseudoXMLgrammatica.aux pseudoXMLgrammatica.log pseudoXMLgrammatica.pdf pseudoXMLgrammatica.dvi pseudoXMLgrammatica.ps pseudoXMLgrammatica

distclean : clean
	rm -f Absyn.h Absyn.c Bison.h Buffer.h Buffer.c pseudoXMLgrammatica.l Lexer.c pseudoXMLgrammatica.y Parser.h Parser.c Test.c Makefile pseudoXMLgrammatica.tex

TestProgram : ${OBJS} TestProgram.o
	@echo "Linking TestProgram..."
	${CC} ${OBJS} TestProgram.o -o TestProgram

Absyn.o : Absyn.c Absyn.h
	${CC} ${CCFLAGS} -c Absyn.c

Buffer.o : Buffer.c Buffer.h
	${CC} ${CCFLAGS} -c Buffer.c

Lexer.c : Lexer.l
	${FLEX} ${FLEX_OPTS} -oLexer.c Lexer.l

Parser.c Bison.h : Parser.y
	${BISON} ${BISON_OPTS} Parser.y -o Parser.c

Lexer.o : CCFLAGS+=-Wno-sign-conversion

Lexer.o : Lexer.c Bison.h
	${CC} ${CCFLAGS} -c Lexer.c

Parser.o : Parser.c Absyn.h Bison.h
	${CC} ${CCFLAGS} -c Parser.c

ReferenceSolver.o : ReferenceSolver.c ParserSupport.h
	${CC} ${CCFLAGS} -c ReferenceSolver.c

ParserSupport.o : ParserSupport.c ParserSupport.h Absyn.h
	${CC} ${CCFLAGS} -c ParserSupport.c

TestProgram.o : TestProgram.c Parser.h Absyn.h
	${CC} ${CCFLAGS} -c TestProgram.c

zip: Absyn.c Absyn.h Bison.h Buffer.c Buffer.h Deletion.c Lexer.l Makefile Parser.h ParserSupport.c ParserSupport.h Parser.y PseudoXML.cf ReferenceSolver.c Test.c tests
	zip ProgettoLC\ parte1\ Gruppo\ 25-3.zip Absyn.c Absyn.h Bison.h Buffer.c Buffer.h Deletion.c Lexer.l Makefile Parser.h ParserSupport.c ParserSupport.h Parser.y PseudoXML.cf ReferenceSolver.c Test.c tests
