-- File generated by the BNF Converter (bnfc 2.9.6.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module SkelPseudoXMLgrammatica where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsPseudoXMLgrammatica

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsPseudoXMLgrammatica.Ident -> Result
transIdent x = case x of
  AbsPseudoXMLgrammatica.Ident string -> failure x

transIdent :: AbsPseudoXMLgrammatica.Ident -> Result
transIdent x = case x of
  AbsPseudoXMLgrammatica.Ident string -> failure x

transSourceFile :: AbsPseudoXMLgrammatica.SourceFile -> Result
transSourceFile x = case x of
  AbsPseudoXMLgrammatica.SourceFile file -> failure x

transFile :: AbsPseudoXMLgrammatica.File -> Result
transFile x = case x of
  AbsPseudoXMLgrammatica.SimpleFile sectiondecls -> failure x
  AbsPseudoXMLgrammatica.FileWImport imports sectiondecls -> failure x

transImport :: AbsPseudoXMLgrammatica.Import -> Result
transImport x = case x of
  AbsPseudoXMLgrammatica.FileImport filepath -> failure x

transFilePath :: AbsPseudoXMLgrammatica.FilePath -> Result
transFilePath x = case x of
  AbsPseudoXMLgrammatica.Path string -> failure x

transSectionDecl :: AbsPseudoXMLgrammatica.SectionDecl -> Result
transSectionDecl x = case x of
  AbsPseudoXMLgrammatica.SectionDecl ident sectioncontent -> failure x

transSectionContent :: AbsPseudoXMLgrammatica.SectionContent -> Result
transSectionContent x = case x of
  AbsPseudoXMLgrammatica.SimpleSecCont fielddecls -> failure x
  AbsPseudoXMLgrammatica.SecContent inherits fielddecls -> failure x

transInherit :: AbsPseudoXMLgrammatica.Inherit -> Result
transInherit x = case x of
  AbsPseudoXMLgrammatica.InheritSection sectionname -> failure x

transSectionName :: AbsPseudoXMLgrammatica.SectionName -> Result
transSectionName x = case x of
  AbsPseudoXMLgrammatica.SecName ident -> failure x

transFieldDecl :: AbsPseudoXMLgrammatica.FieldDecl -> Result
transFieldDecl x = case x of
  AbsPseudoXMLgrammatica.FieldDeclar ident value -> failure x

transValue :: AbsPseudoXMLgrammatica.Value -> Result
transValue x = case x of
  AbsPseudoXMLgrammatica.ValueInt integer -> failure x
  AbsPseudoXMLgrammatica.ValueBool boolean -> failure x
  AbsPseudoXMLgrammatica.ValueString string -> failure x
  AbsPseudoXMLgrammatica.ValueNonLoc nonlocvar -> failure x

transBoolean :: AbsPseudoXMLgrammatica.Boolean -> Result
transBoolean x = case x of
  AbsPseudoXMLgrammatica.Boolean_true -> failure x
  AbsPseudoXMLgrammatica.Boolean_false -> failure x

transNonLocVar :: AbsPseudoXMLgrammatica.NonLocVar -> Result
transNonLocVar x = case x of
  AbsPseudoXMLgrammatica.SimpleNonLoc ident -> failure x
  AbsPseudoXMLgrammatica.NonLoc ident1 ident2 -> failure x
