-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for PrintPseudoXMLgrammatica.

module PrintPseudoXMLgrammatica where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsPseudoXMLgrammatica

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsPseudoXMLgrammatica.Ident where
  prt _ (AbsPseudoXMLgrammatica.Ident i) = doc $ showString i
instance Print AbsPseudoXMLgrammatica.Ident where
  prt _ (AbsPseudoXMLgrammatica.Ident i) = doc $ showString i
instance Print AbsPseudoXMLgrammatica.SourceFile where
  prt i = \case
    AbsPseudoXMLgrammatica.SourceFile file -> prPrec i 0 (concatD [prt 0 file])

instance Print AbsPseudoXMLgrammatica.File where
  prt i = \case
    AbsPseudoXMLgrammatica.SimpleFile sectiondecls -> prPrec i 0 (concatD [prt 0 sectiondecls])
    AbsPseudoXMLgrammatica.FileWImport imports sectiondecls -> prPrec i 0 (concatD [prt 0 imports, prt 0 sectiondecls])

instance Print [AbsPseudoXMLgrammatica.SectionDecl] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString " "), prt 0 xs]

instance Print [AbsPseudoXMLgrammatica.Import] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString " "), prt 0 xs]

instance Print AbsPseudoXMLgrammatica.Import where
  prt i = \case
    AbsPseudoXMLgrammatica.FileImport filepath -> prPrec i 0 (concatD [doc (showString "<import>"), prt 0 filepath, doc (showString "</import>")])

instance Print AbsPseudoXMLgrammatica.FilePath where
  prt i = \case
    AbsPseudoXMLgrammatica.Path str -> prPrec i 0 (concatD [printString str])

instance Print AbsPseudoXMLgrammatica.SectionDecl where
  prt i = \case
    AbsPseudoXMLgrammatica.SectionDecl id_ sectioncontent -> prPrec i 0 (concatD [doc (showString "<section"), doc (showString "name"), doc (showString "="), prt 0 id_, doc (showString ">"), prt 0 sectioncontent, doc (showString "</section>")])

instance Print AbsPseudoXMLgrammatica.SectionContent where
  prt i = \case
    AbsPseudoXMLgrammatica.SimpleSecCont fielddecls -> prPrec i 0 (concatD [prt 0 fielddecls])
    AbsPseudoXMLgrammatica.SecContent inherits fielddecls -> prPrec i 0 (concatD [prt 0 inherits, prt 0 fielddecls])

instance Print [AbsPseudoXMLgrammatica.FieldDecl] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString " "), prt 0 xs]

instance Print [AbsPseudoXMLgrammatica.Inherit] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString " "), prt 0 xs]

instance Print AbsPseudoXMLgrammatica.Inherit where
  prt i = \case
    AbsPseudoXMLgrammatica.InheritSection sectionname -> prPrec i 0 (concatD [doc (showString "<inherit>"), prt 0 sectionname, doc (showString "</inherit>")])

instance Print AbsPseudoXMLgrammatica.SectionName where
  prt i = \case
    AbsPseudoXMLgrammatica.SecName id_ -> prPrec i 0 (concatD [prt 0 id_])

instance Print AbsPseudoXMLgrammatica.FieldDecl where
  prt i = \case
    AbsPseudoXMLgrammatica.FieldDeclar id_ value -> prPrec i 0 (concatD [doc (showString "<field"), doc (showString "name"), doc (showString "="), prt 0 id_, doc (showString ">"), prt 0 value, doc (showString "</field>")])

instance Print AbsPseudoXMLgrammatica.Value where
  prt i = \case
    AbsPseudoXMLgrammatica.ValueInt n -> prPrec i 0 (concatD [prt 0 n])
    AbsPseudoXMLgrammatica.ValueBool boolean -> prPrec i 0 (concatD [prt 0 boolean])
    AbsPseudoXMLgrammatica.ValueString str -> prPrec i 0 (concatD [printString str])
    AbsPseudoXMLgrammatica.ValueNonLoc nonlocvar -> prPrec i 0 (concatD [prt 0 nonlocvar])

instance Print AbsPseudoXMLgrammatica.Boolean where
  prt i = \case
    AbsPseudoXMLgrammatica.Boolean_true -> prPrec i 0 (concatD [doc (showString "true")])
    AbsPseudoXMLgrammatica.Boolean_false -> prPrec i 0 (concatD [doc (showString "false")])

instance Print AbsPseudoXMLgrammatica.NonLocVar where
  prt i = \case
    AbsPseudoXMLgrammatica.SimpleNonLoc id_ -> prPrec i 0 (concatD [doc (showString "$"), prt 0 id_])
    AbsPseudoXMLgrammatica.NonLoc id_1 id_2 -> prPrec i 0 (concatD [doc (showString "$"), prt 0 id_1, doc (showString "."), prt 0 id_2])
