/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef ABSYN_HEADER
#define ABSYN_HEADER

/* strdup was not in the ISO C standard before 6/2019 (C2x), but in POSIX 1003.1.
 * See: https://en.cppreference.com/w/c/experimental/dynamic/strdup
 * Setting _POSIX_C_SOURCE to 200809L activates strdup in string.h.
 */
#define _POSIX_C_SOURCE 200809L

#include <stddef.h>  /* NULL */
#include <string.h>  /* strdup */

/********************   Forward Declarations    ***********************/
struct Value_;
typedef struct Value_ *Value;

struct NonLocVar_;
typedef struct NonLocVar_ *NonLocVar;

/********************   Abstract Syntax Classes    ********************/

struct Value_
{
  enum { is_ValueInt, is_ValueBool, is_ValueString, is_ValueLocal, is_ValueNonLocal} kind;
  union {
    int value_int;
    int value_bool;
    char* value_string;
    char* value_local;
    struct { char* section_name; char* field_name; } value_nonlocal;
  };
};

Value make_ValueInt(int val);
Value make_ValueBool(int val);
Value make_ValueString(char* val);
Value make_ValueLocal(char* field_name);
Value make_ValueNonLocal(char* section_name, char* field_name);


/***************************   Cloning   ******************************/

Value clone_Value(Value p);

/********************   Recursive Destructors    **********************/

/* These free an entire abstract syntax tree
 * including all subtrees and strings.
 *
 * Will not work properly if there is sharing in the tree,
 * i.e., when some pointers are aliased.  In this case
 * it will attempt to free the same memory twice.
 */

void free_Value(Value p);

#endif
