/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include <stdio.h>
#include "Absyn.h"

SourceFile  pSourceFile(FILE *inp);
SourceFile psSourceFile(const char *str);

#endif
