/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include <stdio.h>
#include "Absyn.h"
#include "PseudoXMLParserSupport.h"

SourceFile  pSourceFile(FILE *inp, section_entry** bindings);
SourceFile psSourceFile(const char *str, section_entry** bindings);
SourceFile pnSourceFile(char *filename, section_entry** bindings);

#endif
