/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printSourceFile(SourceFile p)
{
  _n_ = 0;
  bufReset();
  ppSourceFile(p, 0);
  return buf_;
}
char *showSourceFile(SourceFile p)
{
  _n_ = 0;
  bufReset();
  shSourceFile(p);
  return buf_;
}
void ppSourceFile(SourceFile p, int _i_)
{
  switch(p->kind)
  {
  case is_MainFile:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListTopLevelTag(p->u.mainFile_.listtopleveltag_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SourceFile!\n");
    exit(1);
  }
}

void ppListTopLevelTag(ListTopLevelTag listtopleveltag, int i)
{
  if (listtopleveltag == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppTopLevelTag(listtopleveltag->topleveltag_, 0);
    ppListTopLevelTag(listtopleveltag->listtopleveltag_, 0);
  }
}

void ppTopLevelTag(TopLevelTag p, int _i_)
{
  switch(p->kind)
  {
  case is_FileImportTag:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    renderS("import");
    renderC('>');
    ppString(p->u.fileImportTag_.string_, 0);
    renderC('<');
    renderC('/');
    renderS("import");
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SectionTag:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    renderS("section");
    renderS("name");
    renderC('=');
    ppIdent(p->u.sectionTag_.ident_, 0);
    renderC('>');
    ppListSubLevelTag(p->u.sectionTag_.listsubleveltag_, 0);
    renderC('<');
    renderC('/');
    renderS("section");
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing TopLevelTag!\n");
    exit(1);
  }
}

void ppListSubLevelTag(ListSubLevelTag listsubleveltag, int i)
{
  if (listsubleveltag == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppSubLevelTag(listsubleveltag->subleveltag_, 0);
    ppListSubLevelTag(listsubleveltag->listsubleveltag_, 0);
  }
}

void ppSubLevelTag(SubLevelTag p, int _i_)
{
  switch(p->kind)
  {
  case is_FieldTag:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    renderS("field");
    renderS("name");
    renderC('=');
    ppIdent(p->u.fieldTag_.ident_, 0);
    renderC('>');
    ppValue(p->u.fieldTag_.value_, 0);
    renderC('<');
    renderC('/');
    renderS("field");
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_InheritTag:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    renderS("inherit");
    renderC('>');
    ppIdent(p->u.inheritTag_.ident_, 0);
    renderC('<');
    renderC('/');
    renderS("inherit");
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SubLevelTag!\n");
    exit(1);
  }
}

void ppValue(Value p, int _i_)
{
  switch(p->kind)
  {
  case is_ValueInt:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.valueInt_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ValueBool:
    if (_i_ > 0) renderC(_L_PAREN);
    ppBoolean(p->u.valueBool_.boolean_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ValueString:
    if (_i_ > 0) renderC(_L_PAREN);
    ppString(p->u.valueString_.string_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ValueNonLoc:
    if (_i_ > 0) renderC(_L_PAREN);
    ppNonLocVar(p->u.valueNonLoc_.nonlocvar_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Value!\n");
    exit(1);
  }
}

void ppBoolean(Boolean p, int _i_)
{
  switch(p->kind)
  {
  case is_Boolean_true:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("true");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Boolean_false:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("false");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Boolean!\n");
    exit(1);
  }
}

void ppNonLocVar(NonLocVar p, int _i_)
{
  switch(p->kind)
  {
  case is_SimpleNonLoc:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('$');
    ppIdent(p->u.simpleNonLoc_.ident_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_NonLoc:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('$');
    ppIdent(p->u.nonLoc_.ident_1, 0);
    renderC('.');
    ppIdent(p->u.nonLoc_.ident_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing NonLocVar!\n");
    exit(1);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

/* void ppIdent(String s, int i)
{
  renderS(s);
} */


void shSourceFile(SourceFile p)
{
  switch(p->kind)
  {
  case is_MainFile:
    bufAppendC('(');

    bufAppendS("MainFile");

    bufAppendC(' ');

    shListTopLevelTag(p->u.mainFile_.listtopleveltag_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing SourceFile!\n");
    exit(1);
  }
}

void shListTopLevelTag(ListTopLevelTag listtopleveltag)
{
  bufAppendC('[');
  while(listtopleveltag != 0)
  {
    if (listtopleveltag->listtopleveltag_)
    {
      shTopLevelTag(listtopleveltag->topleveltag_);
      bufAppendS(", ");
      listtopleveltag = listtopleveltag->listtopleveltag_;
    }
    else
    {
      shTopLevelTag(listtopleveltag->topleveltag_);
      listtopleveltag = 0;
    }
  }
  bufAppendC(']');
}

void shTopLevelTag(TopLevelTag p)
{
  switch(p->kind)
  {
  case is_FileImportTag:
    bufAppendC('(');

    bufAppendS("FileImportTag");

    bufAppendC(' ');

    shString(p->u.fileImportTag_.string_);

    bufAppendC(')');

    break;
  case is_SectionTag:
    bufAppendC('(');

    bufAppendS("SectionTag");

    bufAppendC(' ');

    shIdent(p->u.sectionTag_.ident_);
  bufAppendC(' ');
    shListSubLevelTag(p->u.sectionTag_.listsubleveltag_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing TopLevelTag!\n");
    exit(1);
  }
}

void shListSubLevelTag(ListSubLevelTag listsubleveltag)
{
  bufAppendC('[');
  while(listsubleveltag != 0)
  {
    if (listsubleveltag->listsubleveltag_)
    {
      shSubLevelTag(listsubleveltag->subleveltag_);
      bufAppendS(", ");
      listsubleveltag = listsubleveltag->listsubleveltag_;
    }
    else
    {
      shSubLevelTag(listsubleveltag->subleveltag_);
      listsubleveltag = 0;
    }
  }
  bufAppendC(']');
}

void shSubLevelTag(SubLevelTag p)
{
  switch(p->kind)
  {
  case is_FieldTag:
    bufAppendC('(');

    bufAppendS("FieldTag");

    bufAppendC(' ');

    shIdent(p->u.fieldTag_.ident_);
  bufAppendC(' ');
    shValue(p->u.fieldTag_.value_);

    bufAppendC(')');

    break;
  case is_InheritTag:
    bufAppendC('(');

    bufAppendS("InheritTag");

    bufAppendC(' ');

    shIdent(p->u.inheritTag_.ident_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing SubLevelTag!\n");
    exit(1);
  }
}

void shValue(Value p)
{
  switch(p->kind)
  {
  case is_ValueInt:
    bufAppendC('(');

    bufAppendS("ValueInt");

    bufAppendC(' ');

    shInteger(p->u.valueInt_.integer_);

    bufAppendC(')');

    break;
  case is_ValueBool:
    bufAppendC('(');

    bufAppendS("ValueBool");

    bufAppendC(' ');

    shBoolean(p->u.valueBool_.boolean_);

    bufAppendC(')');

    break;
  case is_ValueString:
    bufAppendC('(');

    bufAppendS("ValueString");

    bufAppendC(' ');

    shString(p->u.valueString_.string_);

    bufAppendC(')');

    break;
  case is_ValueNonLoc:
    bufAppendC('(');

    bufAppendS("ValueNonLoc");

    bufAppendC(' ');

    shNonLocVar(p->u.valueNonLoc_.nonlocvar_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Value!\n");
    exit(1);
  }
}

void shBoolean(Boolean p)
{
  switch(p->kind)
  {
  case is_Boolean_true:

    bufAppendS("Boolean_true");




    break;
  case is_Boolean_false:

    bufAppendS("Boolean_false");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Boolean!\n");
    exit(1);
  }
}

void shNonLocVar(NonLocVar p)
{
  switch(p->kind)
  {
  case is_SimpleNonLoc:
    bufAppendC('(');

    bufAppendS("SimpleNonLoc");

    bufAppendC(' ');

    shIdent(p->u.simpleNonLoc_.ident_);

    bufAppendC(')');

    break;
  case is_NonLoc:
    bufAppendC('(');

    bufAppendS("NonLoc");

    bufAppendC(' ');

    shIdent(p->u.nonLoc_.ident_1);
  bufAppendC(' ');
    shIdent(p->u.nonLoc_.ident_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing NonLocVar!\n");
    exit(1);
  }
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

/* void shIdent(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
} */


void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

