/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printSourceFile(SourceFile p)
{
  _n_ = 0;
  bufReset();
  ppSourceFile(p, 0);
  return buf_;
}
char *showSourceFile(SourceFile p)
{
  _n_ = 0;
  bufReset();
  shSourceFile(p);
  return buf_;
}
void ppSourceFile(SourceFile p, int _i_)
{
  switch(p->kind)
  {
  case is_MainFile:
    if (_i_ > 0) renderC(_L_PAREN);
    ppFile(p->u.mainFile_.file_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SourceFile!\n");
    exit(1);
  }
}

void ppFile(File p, int _i_)
{
  switch(p->kind)
  {
  case is_SimpleFile:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListSectionDecl(p->u.simpleFile_.listsectiondecl_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_FileWImport:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListImport(p->u.fileWImport_.listimport_, 0);
    ppListSectionDecl(p->u.fileWImport_.listsectiondecl_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing File!\n");
    exit(1);
  }
}

void ppListSectionDecl(ListSectionDecl listsectiondecl, int i)
{
  if (listsectiondecl == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppSectionDecl(listsectiondecl->sectiondecl_, 0);
    ppListSectionDecl(listsectiondecl->listsectiondecl_, 0);
  }
}

void ppListImport(ListImport listimport, int i)
{
  if (listimport == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppImport(listimport->import_, 0);
    ppListImport(listimport->listimport_, 0);
  }
}

void ppImport(Import p, int _i_)
{
  switch(p->kind)
  {
  case is_FileImport:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    renderS("import");
    renderC('>');
    ppFilePath(p->u.fileImport_.filepath_, 0);
    renderC('<');
    renderC('/');
    renderS("import");
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Import!\n");
    exit(1);
  }
}

void ppFilePath(FilePath p, int _i_)
{
  switch(p->kind)
  {
  case is_Path:
    if (_i_ > 0) renderC(_L_PAREN);
    ppString(p->u.path_.string_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing FilePath!\n");
    exit(1);
  }
}

void ppSectionDecl(SectionDecl p, int _i_)
{
  switch(p->kind)
  {
  case is_SecDecl:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    renderS("section");
    renderS("name");
    renderC('=');
    ppIdent(p->u.secDecl_.ident_, 0);
    renderC('>');
    ppSectionContent(p->u.secDecl_.sectioncontent_, 0);
    renderC('<');
    renderC('/');
    renderS("section");
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SectionDecl!\n");
    exit(1);
  }
}

void ppSectionContent(SectionContent p, int _i_)
{
  switch(p->kind)
  {
  case is_SimpleSecCont:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListFieldDecl(p->u.simpleSecCont_.listfielddecl_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SecContent:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListInherit(p->u.secContent_.listinherit_, 0);
    ppListFieldDecl(p->u.secContent_.listfielddecl_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SectionContent!\n");
    exit(1);
  }
}

void ppListFieldDecl(ListFieldDecl listfielddecl, int i)
{
  if (listfielddecl == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppFieldDecl(listfielddecl->fielddecl_, 0);
    ppListFieldDecl(listfielddecl->listfielddecl_, 0);
  }
}

void ppListInherit(ListInherit listinherit, int i)
{
  if (listinherit == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppInherit(listinherit->inherit_, 0);
    ppListInherit(listinherit->listinherit_, 0);
  }
}

void ppInherit(Inherit p, int _i_)
{
  switch(p->kind)
  {
  case is_InheritSection:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    renderS("inherit");
    renderC('>');
    ppIdent(p->u.inheritSection_.ident_, 0);
    renderC('<');
    renderC('/');
    renderS("inherit");
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Inherit!\n");
    exit(1);
  }
}

void ppFieldDecl(FieldDecl p, int _i_)
{
  switch(p->kind)
  {
  case is_FieldDeclar:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    renderS("field");
    renderS("name");
    renderC('=');
    ppIdent(p->u.fieldDeclar_.ident_, 0);
    renderC('>');
    ppValue(p->u.fieldDeclar_.value_, 0);
    renderC('<');
    renderC('/');
    renderS("field");
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing FieldDecl!\n");
    exit(1);
  }
}

void ppValue(Value p, int _i_)
{
  switch(p->kind)
  {
  case is_ValueInt:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.valueInt_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ValueBool:
    if (_i_ > 0) renderC(_L_PAREN);
    ppBoolean(p->u.valueBool_.boolean_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ValueString:
    if (_i_ > 0) renderC(_L_PAREN);
    ppString(p->u.valueString_.string_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ValueNonLoc:
    if (_i_ > 0) renderC(_L_PAREN);
    ppNonLocVar(p->u.valueNonLoc_.nonlocvar_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Value!\n");
    exit(1);
  }
}

void ppBoolean(Boolean p, int _i_)
{
  switch(p->kind)
  {
  case is_Boolean_true:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("true");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Boolean_false:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("false");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Boolean!\n");
    exit(1);
  }
}

void ppNonLocVar(NonLocVar p, int _i_)
{
  switch(p->kind)
  {
  case is_SimpleNonLoc:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('$');
    ppIdent(p->u.simpleNonLoc_.ident_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_NonLoc:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('$');
    ppIdent(p->u.nonLoc_.ident_1, 0);
    renderC('.');
    ppIdent(p->u.nonLoc_.ident_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing NonLocVar!\n");
    exit(1);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void ppIdent(String s, int i)
{
  renderS(s);
}


void shSourceFile(SourceFile p)
{
  switch(p->kind)
  {
  case is_MainFile:
    bufAppendC('(');

    bufAppendS("MainFile");

    bufAppendC(' ');

    shFile(p->u.mainFile_.file_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing SourceFile!\n");
    exit(1);
  }
}

void shFile(File p)
{
  switch(p->kind)
  {
  case is_SimpleFile:
    bufAppendC('(');

    bufAppendS("SimpleFile");

    bufAppendC(' ');

    shListSectionDecl(p->u.simpleFile_.listsectiondecl_);

    bufAppendC(')');

    break;
  case is_FileWImport:
    bufAppendC('(');

    bufAppendS("FileWImport");

    bufAppendC(' ');

    shListImport(p->u.fileWImport_.listimport_);
  bufAppendC(' ');
    shListSectionDecl(p->u.fileWImport_.listsectiondecl_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing File!\n");
    exit(1);
  }
}

void shListSectionDecl(ListSectionDecl listsectiondecl)
{
  bufAppendC('[');
  while(listsectiondecl != 0)
  {
    if (listsectiondecl->listsectiondecl_)
    {
      shSectionDecl(listsectiondecl->sectiondecl_);
      bufAppendS(", ");
      listsectiondecl = listsectiondecl->listsectiondecl_;
    }
    else
    {
      shSectionDecl(listsectiondecl->sectiondecl_);
      listsectiondecl = 0;
    }
  }
  bufAppendC(']');
}

void shListImport(ListImport listimport)
{
  bufAppendC('[');
  while(listimport != 0)
  {
    if (listimport->listimport_)
    {
      shImport(listimport->import_);
      bufAppendS(", ");
      listimport = listimport->listimport_;
    }
    else
    {
      shImport(listimport->import_);
      listimport = 0;
    }
  }
  bufAppendC(']');
}

void shImport(Import p)
{
  switch(p->kind)
  {
  case is_FileImport:
    bufAppendC('(');

    bufAppendS("FileImport");

    bufAppendC(' ');

    shFilePath(p->u.fileImport_.filepath_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Import!\n");
    exit(1);
  }
}

void shFilePath(FilePath p)
{
  switch(p->kind)
  {
  case is_Path:
    bufAppendC('(');

    bufAppendS("Path");

    bufAppendC(' ');

    shString(p->u.path_.string_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing FilePath!\n");
    exit(1);
  }
}

void shSectionDecl(SectionDecl p)
{
  switch(p->kind)
  {
  case is_SecDecl:
    bufAppendC('(');

    bufAppendS("SecDecl");

    bufAppendC(' ');

    shIdent(p->u.secDecl_.ident_);
  bufAppendC(' ');
    shSectionContent(p->u.secDecl_.sectioncontent_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing SectionDecl!\n");
    exit(1);
  }
}

void shSectionContent(SectionContent p)
{
  switch(p->kind)
  {
  case is_SimpleSecCont:
    bufAppendC('(');

    bufAppendS("SimpleSecCont");

    bufAppendC(' ');

    shListFieldDecl(p->u.simpleSecCont_.listfielddecl_);

    bufAppendC(')');

    break;
  case is_SecContent:
    bufAppendC('(');

    bufAppendS("SecContent");

    bufAppendC(' ');

    shListInherit(p->u.secContent_.listinherit_);
  bufAppendC(' ');
    shListFieldDecl(p->u.secContent_.listfielddecl_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing SectionContent!\n");
    exit(1);
  }
}

void shListFieldDecl(ListFieldDecl listfielddecl)
{
  bufAppendC('[');
  while(listfielddecl != 0)
  {
    if (listfielddecl->listfielddecl_)
    {
      shFieldDecl(listfielddecl->fielddecl_);
      bufAppendS(", ");
      listfielddecl = listfielddecl->listfielddecl_;
    }
    else
    {
      shFieldDecl(listfielddecl->fielddecl_);
      listfielddecl = 0;
    }
  }
  bufAppendC(']');
}

void shListInherit(ListInherit listinherit)
{
  bufAppendC('[');
  while(listinherit != 0)
  {
    if (listinherit->listinherit_)
    {
      shInherit(listinherit->inherit_);
      bufAppendS(", ");
      listinherit = listinherit->listinherit_;
    }
    else
    {
      shInherit(listinherit->inherit_);
      listinherit = 0;
    }
  }
  bufAppendC(']');
}

void shInherit(Inherit p)
{
  switch(p->kind)
  {
  case is_InheritSection:
    bufAppendC('(');

    bufAppendS("InheritSection");

    bufAppendC(' ');

    shIdent(p->u.inheritSection_.ident_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Inherit!\n");
    exit(1);
  }
}

void shFieldDecl(FieldDecl p)
{
  switch(p->kind)
  {
  case is_FieldDeclar:
    bufAppendC('(');

    bufAppendS("FieldDeclar");

    bufAppendC(' ');

    shIdent(p->u.fieldDeclar_.ident_);
  bufAppendC(' ');
    shValue(p->u.fieldDeclar_.value_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing FieldDecl!\n");
    exit(1);
  }
}

void shValue(Value p)
{
  switch(p->kind)
  {
  case is_ValueInt:
    bufAppendC('(');

    bufAppendS("ValueInt");

    bufAppendC(' ');

    shInteger(p->u.valueInt_.integer_);

    bufAppendC(')');

    break;
  case is_ValueBool:
    bufAppendC('(');

    bufAppendS("ValueBool");

    bufAppendC(' ');

    shBoolean(p->u.valueBool_.boolean_);

    bufAppendC(')');

    break;
  case is_ValueString:
    bufAppendC('(');

    bufAppendS("ValueString");

    bufAppendC(' ');

    shString(p->u.valueString_.string_);

    bufAppendC(')');

    break;
  case is_ValueNonLoc:
    bufAppendC('(');

    bufAppendS("ValueNonLoc");

    bufAppendC(' ');

    shNonLocVar(p->u.valueNonLoc_.nonlocvar_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Value!\n");
    exit(1);
  }
}

void shBoolean(Boolean p)
{
  switch(p->kind)
  {
  case is_Boolean_true:

    bufAppendS("Boolean_true");




    break;
  case is_Boolean_false:

    bufAppendS("Boolean_false");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Boolean!\n");
    exit(1);
  }
}

void shNonLocVar(NonLocVar p)
{
  switch(p->kind)
  {
  case is_SimpleNonLoc:
    bufAppendC('(');

    bufAppendS("SimpleNonLoc");

    bufAppendC(' ');

    shIdent(p->u.simpleNonLoc_.ident_);

    bufAppendC(')');

    break;
  case is_NonLoc:
    bufAppendC('(');

    bufAppendS("NonLoc");

    bufAppendC(' ');

    shIdent(p->u.nonLoc_.ident_1);
  bufAppendC(' ');
    shIdent(p->u.nonLoc_.ident_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing NonLocVar!\n");
    exit(1);
  }
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void shIdent(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

