/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef PRINTER_HEADER
#define PRINTER_HEADER

#include "Absyn.h"

/* Certain applications may improve performance by changing the buffer size */
#define BUFFER_INITIAL 2048
/* You may wish to change _L_PAREN or _R_PAREN */
#define _L_PAREN '('
#define _R_PAREN ')'

/* The following are simple heuristics for rendering terminals */
/* You may wish to change them */
void renderCC(Char c);
void renderCS(String s);
void indent(void);
void backup(void);
void onEmptyLine(void);
void removeTrailingSpaces(void);
void removeTrailingWhitespace(void);


char *printSourceFile(SourceFile p);

void ppSourceFile(SourceFile p, int i);
void ppFile(File p, int i);
void ppListSectionDecl(ListSectionDecl p, int i);
void ppListImport(ListImport p, int i);
void ppImport(Import p, int i);
void ppFilePath(FilePath p, int i);
void ppSectionDecl(SectionDecl p, int i);
void ppSectionContent(SectionContent p, int i);
void ppListFieldDecl(ListFieldDecl p, int i);
void ppListInherit(ListInherit p, int i);
void ppInherit(Inherit p, int i);
void ppFieldDecl(FieldDecl p, int i);
void ppValue(Value p, int i);
void ppBoolean(Boolean p, int i);
void ppNonLocVar(NonLocVar p, int i);

char *showSourceFile(SourceFile p);

void shSourceFile(SourceFile p);
void shFile(File p);
void shListSectionDecl(ListSectionDecl p);
void shListImport(ListImport p);
void shImport(Import p);
void shFilePath(FilePath p);
void shSectionDecl(SectionDecl p);
void shSectionContent(SectionContent p);
void shListFieldDecl(ListFieldDecl p);
void shListInherit(ListInherit p);
void shInherit(Inherit p);
void shFieldDecl(FieldDecl p);
void shValue(Value p);
void shBoolean(Boolean p);
void shNonLocVar(NonLocVar p);

void ppIdent(String s, int i);
void shIdent(String s);
void ppInteger(Integer n, int i);
void ppDouble(Double d, int i);
void ppChar(Char c, int i);
void ppString(String s, int i);
void ppIdent(String s, int i);
void shInteger(Integer n);
void shDouble(Double d);
void shChar(Char c);
void shString(String s);
void shIdent(String s);
void bufEscapeS(const char *s);
void bufEscapeC(const char c);
void bufAppendS(const char *s);
void bufAppendC(const char c);
void bufReset(void);
void resizeBuffer(void);

#endif

