/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitSourceFile(SourceFile p)
{
  switch(p->kind)
  {
  case is_MainFile:
    /* Code for MainFile Goes Here */
    visitFile(p->u.mainFile_.file_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SourceFile!\n");
    exit(1);
  }
}

void visitFile(File p)
{
  switch(p->kind)
  {
  case is_SimpleFile:
    /* Code for SimpleFile Goes Here */
    visitListSectionDecl(p->u.simpleFile_.listsectiondecl_);
    break;
  case is_FileWImport:
    /* Code for FileWImport Goes Here */
    visitListImport(p->u.fileWImport_.listimport_);
    visitListSectionDecl(p->u.fileWImport_.listsectiondecl_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing File!\n");
    exit(1);
  }
}

void visitListSectionDecl(ListSectionDecl listsectiondecl)
{
  while(listsectiondecl  != 0)
  {
    /* Code For ListSectionDecl Goes Here */
    visitSectionDecl(listsectiondecl->sectiondecl_);
    listsectiondecl = listsectiondecl->listsectiondecl_;
  }
}

void visitListImport(ListImport listimport)
{
  while(listimport  != 0)
  {
    /* Code For ListImport Goes Here */
    visitImport(listimport->import_);
    listimport = listimport->listimport_;
  }
}

void visitImport(Import p)
{
  switch(p->kind)
  {
  case is_FileImport:
    /* Code for FileImport Goes Here */
    visitFilePath(p->u.fileImport_.filepath_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Import!\n");
    exit(1);
  }
}

void visitFilePath(FilePath p)
{
  switch(p->kind)
  {
  case is_Path:
    /* Code for Path Goes Here */
    visitString(p->u.path_.string_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing FilePath!\n");
    exit(1);
  }
}

void visitSectionDecl(SectionDecl p)
{
  switch(p->kind)
  {
  case is_SecDecl:
    /* Code for SecDecl Goes Here */
    visitIdent(p->u.secDecl_.ident_);
    visitSectionContent(p->u.secDecl_.sectioncontent_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SectionDecl!\n");
    exit(1);
  }
}

void visitSectionContent(SectionContent p)
{
  switch(p->kind)
  {
  case is_SimpleSecCont:
    /* Code for SimpleSecCont Goes Here */
    visitListFieldDecl(p->u.simpleSecCont_.listfielddecl_);
    break;
  case is_SecContent:
    /* Code for SecContent Goes Here */
    visitListInherit(p->u.secContent_.listinherit_);
    visitListFieldDecl(p->u.secContent_.listfielddecl_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SectionContent!\n");
    exit(1);
  }
}

void visitListFieldDecl(ListFieldDecl listfielddecl)
{
  while(listfielddecl  != 0)
  {
    /* Code For ListFieldDecl Goes Here */
    visitFieldDecl(listfielddecl->fielddecl_);
    listfielddecl = listfielddecl->listfielddecl_;
  }
}

void visitListInherit(ListInherit listinherit)
{
  while(listinherit  != 0)
  {
    /* Code For ListInherit Goes Here */
    visitInherit(listinherit->inherit_);
    listinherit = listinherit->listinherit_;
  }
}

void visitInherit(Inherit p)
{
  switch(p->kind)
  {
  case is_InheritSection:
    /* Code for InheritSection Goes Here */
    visitIdent(p->u.inheritSection_.ident_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Inherit!\n");
    exit(1);
  }
}

void visitFieldDecl(FieldDecl p)
{
  switch(p->kind)
  {
  case is_FieldDeclar:
    /* Code for FieldDeclar Goes Here */
    visitIdent(p->u.fieldDeclar_.ident_);
    visitValue(p->u.fieldDeclar_.value_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing FieldDecl!\n");
    exit(1);
  }
}

void visitValue(Value p)
{
  switch(p->kind)
  {
  case is_ValueInt:
    /* Code for ValueInt Goes Here */
    visitInteger(p->u.valueInt_.integer_);
    break;
  case is_ValueBool:
    /* Code for ValueBool Goes Here */
    visitBoolean(p->u.valueBool_.boolean_);
    break;
  case is_ValueString:
    /* Code for ValueString Goes Here */
    visitString(p->u.valueString_.string_);
    break;
  case is_ValueNonLoc:
    /* Code for ValueNonLoc Goes Here */
    visitNonLocVar(p->u.valueNonLoc_.nonlocvar_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Value!\n");
    exit(1);
  }
}

void visitBoolean(Boolean p)
{
  switch(p->kind)
  {
  case is_Boolean_true:
    /* Code for Boolean_true Goes Here */
    break;
  case is_Boolean_false:
    /* Code for Boolean_false Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Boolean!\n");
    exit(1);
  }
}

void visitNonLocVar(NonLocVar p)
{
  switch(p->kind)
  {
  case is_SimpleNonLoc:
    /* Code for SimpleNonLoc Goes Here */
    visitIdent(p->u.simpleNonLoc_.ident_);
    break;
  case is_NonLoc:
    /* Code for NonLoc Goes Here */
    visitIdent(p->u.nonLoc_.ident_1);
    visitIdent(p->u.nonLoc_.ident_2);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing NonLocVar!\n");
    exit(1);
  }
}

void visitIdent(Ident p)
{
  /* Code for Ident Goes Here */
}
void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

