/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitSourceFile(SourceFile p)
{
  switch(p->kind)
  {
  case is_MainFile:
    /* Code for MainFile Goes Here */
    visitListTopLevelTag(p->u.mainFile_.listtopleveltag_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SourceFile!\n");
    exit(1);
  }
}

void visitListTopLevelTag(ListTopLevelTag listtopleveltag)
{
  while(listtopleveltag  != 0)
  {
    /* Code For ListTopLevelTag Goes Here */
    visitTopLevelTag(listtopleveltag->topleveltag_);
    listtopleveltag = listtopleveltag->listtopleveltag_;
  }
}

void visitTopLevelTag(TopLevelTag p)
{
  switch(p->kind)
  {
  case is_FileImportTag:
    /* Code for FileImportTag Goes Here */
    visitString(p->u.fileImportTag_.string_);
    break;
  case is_SectionTag:
    /* Code for SectionTag Goes Here */
    visitIdent(p->u.sectionTag_.ident_);
    visitListSubLevelTag(p->u.sectionTag_.listsubleveltag_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing TopLevelTag!\n");
    exit(1);
  }
}

void visitListSubLevelTag(ListSubLevelTag listsubleveltag)
{
  while(listsubleveltag  != 0)
  {
    /* Code For ListSubLevelTag Goes Here */
    visitSubLevelTag(listsubleveltag->subleveltag_);
    listsubleveltag = listsubleveltag->listsubleveltag_;
  }
}

void visitSubLevelTag(SubLevelTag p)
{
  switch(p->kind)
  {
  case is_FieldTag:
    /* Code for FieldTag Goes Here */
    visitIdent(p->u.fieldTag_.ident_);
    visitValue(p->u.fieldTag_.value_);
    break;
  case is_InheritTag:
    /* Code for InheritTag Goes Here */
    visitIdent(p->u.inheritTag_.ident_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SubLevelTag!\n");
    exit(1);
  }
}

void visitValue(Value p)
{
  switch(p->kind)
  {
  case is_ValueInt:
    /* Code for ValueInt Goes Here */
    visitInteger(p->u.valueInt_.integer_);
    break;
  case is_ValueBool:
    /* Code for ValueBool Goes Here */
    visitBoolean(p->u.valueBool_.boolean_);
    break;
  case is_ValueString:
    /* Code for ValueString Goes Here */
    visitString(p->u.valueString_.string_);
    break;
  case is_ValueNonLoc:
    /* Code for ValueNonLoc Goes Here */
    visitNonLocVar(p->u.valueNonLoc_.nonlocvar_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Value!\n");
    exit(1);
  }
}

void visitBoolean(Boolean p)
{
  switch(p->kind)
  {
  case is_Boolean_true:
    /* Code for Boolean_true Goes Here */
    break;
  case is_Boolean_false:
    /* Code for Boolean_false Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Boolean!\n");
    exit(1);
  }
}

void visitNonLocVar(NonLocVar p)
{
  switch(p->kind)
  {
  case is_SimpleNonLoc:
    /* Code for SimpleNonLoc Goes Here */
    visitIdent(p->u.simpleNonLoc_.ident_);
    break;
  case is_NonLoc:
    /* Code for NonLoc Goes Here */
    visitIdent(p->u.nonLoc_.ident_1);
    visitIdent(p->u.nonLoc_.ident_2);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing NonLocVar!\n");
    exit(1);
  }
}

void visitIdent(Ident p)
{
  /* Code for Ident Goes Here */
}
void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

