/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef SKELETON_HEADER
#define SKELETON_HEADER
/* You might want to change the above name. */

#include "Absyn.h"


void visitSourceFile(SourceFile p);
void visitFile(File p);
void visitListSectionDecl(ListSectionDecl p);
void visitListImport(ListImport p);
void visitImport(Import p);
void visitFilePath(FilePath p);
void visitSectionDecl(SectionDecl p);
void visitSectionContent(SectionContent p);
void visitListFieldDecl(ListFieldDecl p);
void visitListInherit(ListInherit p);
void visitInherit(Inherit p);
void visitFieldDecl(FieldDecl p);
void visitValue(Value p);
void visitBoolean(Boolean p);
void visitNonLocVar(NonLocVar p);

void visitIdent(Ident p);
void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

