/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef SKELETON_HEADER
#define SKELETON_HEADER
/* You might want to change the above name. */

#include "Absyn.h"


void visitSourceFile(SourceFile p);
void visitListTopLevelTag(ListTopLevelTag p);
void visitTopLevelTag(TopLevelTag p);
void visitListSubLevelTag(ListSubLevelTag p);
void visitSubLevelTag(SubLevelTag p);
void visitValue(Value p);
void visitBoolean(Boolean p);
void visitNonLocVar(NonLocVar p);

void visitIdent(Ident p);
void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

